---
- name: Download vip rbac manifest to first master
  ansible.builtin.get_url:
    url: "https://kube-vip.io/manifests/rbac.yaml"
    dest: "/var/lib/rancher/k3s/server/manifests/vip-rbac.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['server'][0]]['ansible_hostname']

- name: Copy vip manifest to first master
  template:
    src: "kube-vip.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/kube-vip.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == hostvars[groups['server'][0]]['ansible_hostname']