---
- name: Copy k3s.yaml from remote host to local machine
  hosts: "{{ groups['server'][0] }}"   # Replace with your target host or group
  become: yes              # Elevate privileges to access the file if necessary
  tasks:
    - name: Fetch k3s.yaml from remote host
      fetch:
        src: /etc/rancher/k3s/k3s.yaml  # Path to the file on the remote host
        dest: ./     # Local path to store the file (relative to the directory where you run the playbook)
        flat: yes                       # Ensures the file is not saved inside a folder structure based on the host name
    - name: Modify the server address in the k3s.yaml file
      ansible.builtin.command:
        cmd: "sed -i 's|server: https://127.0.0.1:6443|server: https://192.168.1.12:6443|' ./k3s.yaml"
      delegate_to: localhost