---
- name: Install NFS server dependencies
  hosts: k3s_cluster
  become: true

  tasks:
    - name: Install NFS client packages for Rocky Linux
      dnf:
        name: 
          - nfs-utils
          - rpcbind
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure NFS services are running
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - rpcbind
        - nfs-utils
      when: ansible_os_family == "RedHat"