---
- name: Set permissions for PVC directory on all nodes
  hosts: k3s_cluster  
  become: true  

  tasks:
    - name: Ensure the directory exists
      file:
        path: /opt/local-path-provisioner
        state: directory
        mode: '0777'

    - name: Set permissions to 777 for the PVC directory
      ansible.builtin.command:
        cmd: chmod -R 777 /opt/local-path-provisioner-rwx

    - name: Verify permissions of the directory
      ansible.builtin.command:
        cmd: ls -ld /opt/local-path-provisioner
      register: dir_listing

    - name: Display directory permissions
      debug:
        msg: "{{ dir_listing.stdout }}"

    - name: Ensure the directory exists
      file:
        path: /var/loki
        state: directory
        mode: '0777'

    - name: Set permissions to 777 for the PVC directory
      ansible.builtin.command:
        cmd: chmod -R 777 /var/loki

    - name: Ensure the loki compactor directory exists
      file:
        path: /var/loki/compactor
        state: directory
        mode: '0777'

    - name: Ensure the boltdb-shipper-active directory exists
      file:
        path: /var/loki/boltdb-shipper-active
        state: directory
        mode: '0777'

    
